// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"time"

	"github.com/google/uuid"
)

type CategoriesCategories struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Level     int32     `json:"level"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type CategoriesCategoryClosure struct {
	Ancestor   uuid.UUID `json:"ancestor"`
	Descendant uuid.UUID `json:"descendant"`
	Depth      int32     `json:"depth"`
}
