services:

  citus:
    # image: citusdata/citus:13
    image: citusdata/citus:latest
    container_name: citus
    platform: linux/amd64
    restart: on-failure:5
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: ecommerce
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ecommerce" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      app-network:

volumes:
  data:

networks:
  app-network:
    external: true
