// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentsPayments struct {
	PaymentID   uuid.UUID      `json:"paymentID"`
	OrderID     uuid.UUID      `json:"orderID"`
	Amount      pgtype.Numeric `json:"amount"`
	Currency    string         `json:"currency"`
	Method      string         `json:"method"`
	Status      string         `json:"status"`
	GatewayTxID *string        `json:"gatewayTxID"`
	Metadata    []byte         `json:"metadata"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}
