services:

  gateway:
    image: example/kratos/gateway:v1.4.0
    ports:
      - "8080:8080"
    container_name: ecommerce-gateway
    platform: linux/amd64
    pull_policy: always
    restart: on-failure:3
    environment:
      - discoveryDsn=consul://localhost:8500
      - configPath=ecommerce/gateway/config.yaml
      - jwtPubkeyPath=/app/dynamic-config/public.pem
      - certFile=/app/dynamic-config/tls/gateway.crt
      - keyFile=/app/dynamic-config/tls/gateway.key
      - RBAC_MODEL=/app/dynamic-config/rbac_model.conf
    # 把配置文件挂载到容器中, 线上服务器需要 ./cmd/gateway 目录改成配置文件的路径
    volumes:
      - ./:/app/dynamic-config
    command:
      - "/app/gateway"
      - "-conf"
      - "/app/configs/config.yaml"
    networks:
      - ecommerce

  auth:
    image: example/repo/auth:dev
    platform: linux/amd64
    ports:
      - "30002:30002"
    container_name: ecommerce-auth-v1
    restart: on-failure:3
    environment:
      config_center: localhost:8500
    networks:
      - ecommerce
    command:
      - "/app/service"

  user:
    image: example/repo/user:dev
    platform: linux/amd64
    ports:
      - "30003:30003"
    container_name: ecommerce-user-v1
    restart: on-failure:3
    environment:
      config_center: localhost:8500
    networks:
      - ecommerce

  product:
    platform: linux/amd64
    image: example/repo/product:dev
    ports:
      - "30005:30005"
      - "30006:30006"
    container_name: ecommerce-product-v1
    restart: on-failure:3
    environment:
      config_center: localhost:8500
    networks:
      - ecommerce

  cart:
    image: example/repo/cart:dev
    platform: linux/amd64
    ports:
      - "30007:30007"
      - "30008:30008"
    container_name: ecommerce-cart-v1
    restart: on-failure:3
    environment:
      config_center: localhost:8500
    networks:
      - ecommerce

  order:
    image: example/repo/order:dev
    platform: linux/amd64
    ports:
      - "30009:30009"
      - "30010:30010"
    container_name: ecommerce-order-v1
    restart: on-failure:3
    environment:
      config_center: localhost:8500
    networks:
      - ecommerce

  checkout:
    image: example/repo/checkout:dev
    platform: linux/amd64
    ports:
      - "30011:30011"
      - "30012:30012"
    container_name: ecommerce-checkout-v1
    restart: on-failure:3
    environment:
      config_center: localhost:8500
    networks:
      - ecommerce

  payment:
    image: example/repo/payment:dev
    platform: linux/amd64
    ports:
      - "30014:30014"
    container_name: ecommerce-payment-v1
    restart: on-failure:3
    environment:
      config_center: localhost:8500
    networks:
      - ecommerce

  category:
    image: example/repo/category:dev
    platform: linux/amd64
    ports:
      - "30016:30016"
    container_name: ecommerce-category-v1
    restart: on-failure:3
    environment:
      config_center: localhost:8500
    networks:
      - ecommerce

#  assistant:
#    image: example/repo/assistant:dev
#    platform: linux/amd64
#    ports:
#      - "30017:30017"
#      - "30018:30018"
#    container_name: ecommerce-assistant-v1
#    restart: on-failure:3
#    environment:
#      config_center: localhost:8500

networks:
  ecommerce:
    external:
      name: ecommerce
