// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend/application/payment/internal/biz"
	"backend/application/payment/internal/conf"
	"backend/application/payment/internal/data"
	"backend/application/payment/internal/server"
	"backend/application/payment/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, consul *conf.Consul, observability *conf.Observability, logger log.Logger) (*kratos.App, func(), error) {
	pool := data.NewDB(confData)
	client := data.NewCache(confData)
	dataData, cleanup, err := data.NewData(pool, client, logger)
	if err != nil {
		return nil, nil, err
	}
	paymentRepo := data.NewPaymentRepo(dataData, logger)
	paymentUsecase := biz.NewPaymentUsecase(paymentRepo, logger)
	paymentService := service.NewPaymentService(paymentUsecase)
	grpcServer := server.NewGRPCServer(paymentService, confServer, observability, logger)
	registrar := server.NewRegistrar(consul)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
