services:

  citus:
    image: citusdata/citus:postgres_16
    container_name: citus
    platform: linux/amd64
    restart: on-failure:5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: citus
