// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend/application/merchant/internal/biz"
	"backend/application/merchant/internal/conf"
	"backend/application/merchant/internal/data"
	"backend/application/merchant/internal/server"
	"backend/application/merchant/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, consul *conf.Consul, observability *conf.Observability, logger log.Logger) (*kratos.App, func(), error) {
	pool := data.NewDB(confData)
	client := data.NewCache(confData)
	dataData, cleanup, err := data.NewData(pool, client, logger)
	if err != nil {
		return nil, nil, err
	}
	inventoryRepo := data.NewInventoryRepo(dataData, logger)
	inventoryUsecase := biz.NewInventoryUsecase(inventoryRepo, logger)
	productRepo := data.NewProductRepo(dataData, logger)
	productUsecase := biz.NewProductUsecase(productRepo, logger)
	inventoryService := service.NewInventoryService(inventoryUsecase, productUsecase)
	productService := service.NewProductService(productUsecase)
	grpcServer := server.NewGRPCServer(confServer, observability, logger, inventoryService, productService)
	httpServer := server.NewHTTPServer(confServer, observability, logger, inventoryService, productService)
	registrar := server.NewRegistrar(consul)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
