apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos-template
  labels:
    app: kratos-template
spec:
  template:
    spec:
      containers:
        - name: kratos-template
          resources:
            limits:
              memory: "50Mi"
              cpu: "50m"
