// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MerchantAddresses struct {
	ID            int64
	MerchantID    uuid.UUID
	AddressType   string
	ContactPerson string
	ContactPhone  string
	StreetAddress string
	City          string
	State         string
	Country       string
	ZipCode       string
	IsDefault     bool
	Remarks       string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type MerchantStockAdjustments struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	MerchantID uuid.UUID
	Quantity   int32
	Reason     *string
	OperatorID uuid.UUID
	CreatedAt  pgtype.Timestamptz
}

type MerchantStockAlerts struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	MerchantID uuid.UUID
	Threshold  int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
