// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CartsCart struct {
	CartID    int32            `json:"cartID"`
	UserID    uuid.UUID        `json:"userID"`
	CartName  string           `json:"cartName"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type CartsCartItems struct {
	CartItemID uuid.UUID        `json:"cartItemID"`
	CartID     int32            `json:"cartID"`
	MerchantID uuid.UUID        `json:"merchantID"`
	ProductID  uuid.UUID        `json:"productID"`
	Quantity   int32            `json:"quantity"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
}
