// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

type UsersAddresses struct {
	ID            int32  `json:"id"`
	Owner         string `json:"owner"`
	Name          string `json:"name"`
	StreetAddress string `json:"streetAddress"`
	City          string `json:"city"`
	State         string `json:"state"`
	Country       string `json:"country"`
	ZipCode       string `json:"zipCode"`
}
